CREATE DATABASE IF NOT EXISTS job_board;
USE job_board;

CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
role ENUM('job_seeker', 'employer') NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);